### ISSUE TITLE
You should not use <Switch> outside a <Router>

### ISSUE THREAD

**Issue by herechc** [ctrlplusb/react-tree-walker#49]
Hi，i use react-async-bootstrapper on ssr，and it return
`
Error: Invariant failed: You should not use <Switch> outside a <Router>
    at invariant (E:\yx\react\todo\react-ssr\node_modules\_tiny-invariant@1.0.4@tiny-invariant\dist\tiny-invariant.cjs.js:13:11)
    at Object.children (E:\yx\react\todo\react-ssr\node_modules\_react-router@5.0.0@react-router\cjs\react-router.js:672:21)
    at recursive (E:\yx\react\todo\react-ssr\node_modules\_react-tree-walker@4.3.0@react-tree-walker\dist\react-tree-walker.js:129:41)
    at E:\yx\react\todo\react-ssr\node_modules\_react-tree-walker@4.3.0@react-tree-walker\dist\react-tree-walker.js:153:26
    at process._tickCallback (internal/process/next_tick.js:68:7)
`
my code： 
``` <Provider {...stores}>
      <StaticRouter context={routerContext} location={url}>
        <App></App>
      </StaticRouter>
    </Provider>
```

```
const App = () => (
  <Switch>
    <Route exact path="/" component={Default} />
  </Switch>
)
```

```
return new Promise((resolve, reject) => {
    asyncBootstrapper(app).then(() => {
      if (routerContext.url) {
        res.status(302).setHeader('Location', routerContext.url)
        res.end();
        return;
      }
      const appString = ReactDomServer.renderToString(app); 
      const helmet = Helmet.rewind();
      let html = ejs.render(template, {
        meta: helmet.meta.toString(),
        link: helmet.link.toString(),
        style: helmet.style.toString(),
        title: helmet.title.toString(),
        appString,
        stylesString,
        scriptsString,
        initalState: serialize(getStoreState(storeMap)),
      });
      res.send(html);
      resolve();
    }).catch(reject)
  })
```

**Comment by herechc** [comment]
I had already solved it， I Modify the version of “react-router-dom” from ’5.0.0‘ to ’4.3.1‘；It works
